### ISSUE TITLE
Channels list should match that of the original `environment.yaml`

### ISSUE THREAD

**Issue by itamarst** [Simplistix/picky-conda#3]
Right now channels are stored in sorted order in `environment.lock.yaml`; they should instead be in the same order they were in the original `environment.yml` so that priorities are correct.

```shell-session
$ picky lock
$ head environment.yml
name: example
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.0
# ...
$ head environment.lock.yaml
name: example
channels:
- conda-forge
- defaults
- simplistix
# ...
```

**Comment by cjw296** [comment]
I remember this being because conda's export returned the channels in a non-deterministic order.
If that's changed, and env export now reports the channels in priority order, that would be great and the sort can be removed.

The first step would be to go digging in conda's export code and verify that the channels are now exported in actual priority order. I believe conda *does* have channel priority order, just not sure it's reflected in what's exported from `conda env export`.

Another thing to check: is the order of channels in `environment.yaml` actually used as their priority? I mean, I know a list is ordered, but conda is a complicated beast under the covers...

**Comment by itamarst** [comment]
1. I verified that order matters; if you put `defaults` first you get different packages installed than if `conda-forge` is first, AFAICT (you can verify).

2. Conda's export order is due to a bug: https://github.com/conda/conda/issues/7238

3. The correct behavior is to load the original `environment.yml` and copy the order there, rather than sorting.

**Comment by cjw296** [comment]
Cool, do you reckon you could work up a patch to fix this? I think there's already a test that should fail when you do, but might be worth adding a couple more to be explicit...

**Comment by hackalog** [comment]
Are you still interested in this happening? I'm doing this for my own project (github.com/hackalog/easydata), but I could likely port this behavior back to picky if you're still using it.

**Comment by itamarst** [comment]
Personally I'm not using it (and I've been recommending `conda-lock` for people who don't use `pip`, since it's nice and fast and not platform-specific). But `pip` support is a useful thing to have for some people.

**Comment by cjw296** [comment]
Assuming `conda-lock` is https://github.com/conda-incubator/conda-lock, that looks like a good option! (and seems to indicate it supports pip, @itamarst is there a particular reason to avoid it when using pip?)

@hackalog - I'm aware I owe you an email! Working on that now :-)

**Comment by itamarst** [comment]
Oh, cool. Looks like `pip` support was added 3 weeks ago (https://github.com/conda-incubator/conda-lock/pull/124). Gotta go update a bunch of places accordingly.

**Comment by cjw296** [comment]
Okay, let's officially go for https://github.com/conda-incubator/conda-lock
